package com.snc.entity;

public class PiwikUrlModule {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piwik_url_module.idsite
     *
     * @mbggenerated
     */
    private Integer idsite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piwik_url_module.url_id
     *
     * @mbggenerated
     */
    private Integer urlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piwik_url_module.module_id
     *
     * @mbggenerated
     */
    private Integer moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piwik_url_module.idsite
     *
     * @return the value of piwik_url_module.idsite
     *
     * @mbggenerated
     */
    public Integer getIdsite() {
        return idsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piwik_url_module.idsite
     *
     * @param idsite the value for piwik_url_module.idsite
     *
     * @mbggenerated
     */
    public void setIdsite(Integer idsite) {
        this.idsite = idsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piwik_url_module.url_id
     *
     * @return the value of piwik_url_module.url_id
     *
     * @mbggenerated
     */
    public Integer getUrlId() {
        return urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piwik_url_module.url_id
     *
     * @param urlId the value for piwik_url_module.url_id
     *
     * @mbggenerated
     */
    public void setUrlId(Integer urlId) {
        this.urlId = urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piwik_url_module.module_id
     *
     * @return the value of piwik_url_module.module_id
     *
     * @mbggenerated
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piwik_url_module.module_id
     *
     * @param moduleId the value for piwik_url_module.module_id
     *
     * @mbggenerated
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piwik_url_module.url_name
     *
     * @mbggenerated
     */
    private String urlName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piwik_url_module.module_name
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piwik_url_module.url_name
     *
     * @return the value of piwik_url_module.url_name
     *
     * @mbggenerated
     */
    public String getUrlName() {
        return urlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piwik_url_module.url_name
     *
     * @param urlName the value for piwik_url_module.url_name
     *
     * @mbggenerated
     */
    public void setUrlName(String urlName) {
        this.urlName = urlName == null ? null : urlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piwik_url_module.module_name
     *
     * @return the value of piwik_url_module.module_name
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piwik_url_module.module_name
     *
     * @param moduleName the value for piwik_url_module.module_name
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }
}