package com.snc.entity;

public class PiwikLogAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piwik_log_action.idaction
     *
     * @mbggenerated
     */
    private Integer idaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piwik_log_action.hash
     *
     * @mbggenerated
     */
    private Integer hash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piwik_log_action.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piwik_log_action.url_prefix
     *
     * @mbggenerated
     */
    private Byte urlPrefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piwik_log_action.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piwik_log_action.idaction
     *
     * @return the value of piwik_log_action.idaction
     *
     * @mbggenerated
     */
    public Integer getIdaction() {
        return idaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piwik_log_action.idaction
     *
     * @param idaction the value for piwik_log_action.idaction
     *
     * @mbggenerated
     */
    public void setIdaction(Integer idaction) {
        this.idaction = idaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piwik_log_action.hash
     *
     * @return the value of piwik_log_action.hash
     *
     * @mbggenerated
     */
    public Integer getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piwik_log_action.hash
     *
     * @param hash the value for piwik_log_action.hash
     *
     * @mbggenerated
     */
    public void setHash(Integer hash) {
        this.hash = hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piwik_log_action.type
     *
     * @return the value of piwik_log_action.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piwik_log_action.type
     *
     * @param type the value for piwik_log_action.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piwik_log_action.url_prefix
     *
     * @return the value of piwik_log_action.url_prefix
     *
     * @mbggenerated
     */
    public Byte getUrlPrefix() {
        return urlPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piwik_log_action.url_prefix
     *
     * @param urlPrefix the value for piwik_log_action.url_prefix
     *
     * @mbggenerated
     */
    public void setUrlPrefix(Byte urlPrefix) {
        this.urlPrefix = urlPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piwik_log_action.name
     *
     * @return the value of piwik_log_action.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piwik_log_action.name
     *
     * @param name the value for piwik_log_action.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public String toString() {
        return "PiwikLogAction{" +
                "idaction=" + idaction +
                ", hash=" + hash +
                ", type=" + type +
                ", urlPrefix=" + urlPrefix +
                ", name='" + name + '\'' +
                '}';
    }
}