package com.snc.dao;

import com.snc.entity.PiwikVariable;
import org.apache.ibatis.annotations.Param;

public interface PiwikVariableDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piwik_variable
     *
     * @mbggenerated
     */
    int insert(PiwikVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piwik_variable
     *
     * @mbggenerated
     */
    int insertSelective(PiwikVariable record);

    /**
     * 根据name更新value值
     * @param piwikVariable
     * @return
     */
    int updateValue(PiwikVariable piwikVariable);

    /**
     * 查询指定name的value值
     * @param name
     * @return
     */
    String selectByName(@Param("name") String name);
}