package com.snc.dao;

import com.snc.entity.PiwikUrlModule;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PiwikUrlModuleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piwik_url_module
     *
     * @mbggenerated
     */
    int insert(PiwikUrlModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piwik_url_module
     *
     * @mbggenerated
     */
    int insertSelective(PiwikUrlModule record);

    /**
     * 插入指定sql查询数据
     * @return
     */
    int insertUrlModule();

    /**
     * 清空数据
     * @return
     */
    int deleteAll();

    /**
     * 查询模块名
     * @param url
     * @return
     */
    List<String> selectModuleByUrl(@Param("url") String url);

    /**
     * 查询url
     * @param module 模块名
     * @return
     */
    List<String> selectUrlByModule(@Param("module") String module);
}